### ISSUE TITLE
Add Space B/w Subscribe box and Trending Topics

### ISSUE THREAD

**Issue by Tooba-Amjad** [Niraj-1729/Hacktoberfest-2023#2]
Add Space B/w Subscribe box and Trending Topics
**Before**
![Screenshot (157)](https://github.com/Niraj-1729/Hacktoberfest-2023/assets/106931048/f59b48f3-53f3-4c82-bf3a-f20b4f4eafef)
**After**

![Screenshot (159)](https://github.com/Niraj-1729/Hacktoberfest-2023/assets/106931048/4db191a3-2aac-4737-83d9-2d05e001fd2a)

Add this issue under hacktoberfest @Niraj-1729

**Comment by Tooba-Amjad** [comment]
Add this issue under Hacktoberfest 
and Asssigned it to me 
I'll do it mins

**Comment by Niraj-1729** [comment]
It will be great to get your contribution, go for it to resolve it. 
Happy coding !!
